import type { Metadata } from "next";
import { Oswald, Space_Grotesk } from "next/font/google";
import "./globals.css";

const geist = Space_Grotesk({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700"],
  variable: "--geist",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Heart-Disease",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // This is the root layout for the application.
  return (
    <html lang="en" className="bg-black" suppressHydrationWarning>
      <body className={`${geist.className}`}>{children}</body>
    </html>
  );
}
