import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Particles } from "@/components/magicui/particles";

const geist = Geist({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700", "800", "900"],
  variable: "--geist",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Heart-Disease",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black" suppressHydrationWarning>

      <body className={`${geist.className} `}>{children}</body>
    </html>
  );
}
