FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Ganti ke 8080 karena Cloud Run hanya menerima trafik di port ini
EXPOSE 8080

# Gunakan ENV agar bisa mengikuti port yang diberikan Cloud Run
CMD ["sh", "-c", "uvicorn app:app --host 0.0.0.0 --port ${PORT:-8080}"]

