FROM python:3.10
# Buat working directory
WORKDIR /app

# Salin file requirements dan install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Salin semua file ke dalam container
COPY . .

# Ekspos port (ubah kalau kamu pakai selain 8000)
EXPOSE 8000

# Jalankan FastAPI dengan uvicorn (file app.py, objek bernama app)
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
