export const normalizeInput = (data: Record<string, any>) => ({
  HighBP: data.HighBP ?? 0,
  HighChol: data.HighChol ?? 0,
  CholCheck: data.CholCheck ?? 0,
  BMI: data.BMI ?? 0,
  Smoker: data.Smoker ?? 0,
  Stroke: data.Stroke ?? 0,
  Diabetes: data.Diabetes ?? 0,
  PhysActivity: data.PhysActivity ?? 0,
  Fruits: data.Fruits ?? 0,
  Veggies: data.Veggies ?? 0,
  HvyAlcoholConsump: data.HvyAlcoholConsump ?? 0,
  AnyHealthcare: data.AnyHealthcare ?? 0,
  NoDocbcCost: data.NoDocbcCost ?? 0,
  GenHlth: data.GenHlth ?? 0,
  MentHlth: data.MentHlth ?? 0,
  PhysHlth: data.PhysHlth ?? 0,
  DiffWalk: data.DiffWalk ?? 0,
  Sex: data.Sex ?? 0,
  Age: data.Age ?? 0,
  Education: data.Education ?? 0,
  Income: data.Income ?? 0,
});
